# Generated by Django 5.0.6 on 2024-06-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_app', '0007_alter_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='customer_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
