# Generated by Django 5.0.6 on 2024-06-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_app', '0010_alter_payment_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='customer_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
