# Generated by Django 5.0.6 on 2024-06-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_app', '0012_alter_payment_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ephemeral_key',
            field=models.CharField(default='', max_length=255),
        ),
    ]
